GolfController/Models/Hole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GolfController.Models
{
    public class Course
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int  NumberOfHoles { get; set; }
        public int TotalLength { get; set; }
        public  int TotalPar { get; set; }
        public virtual ICollection<Hole> holes { get; set; }


    }

    public class Hole
    {
        public int ID { get; set; }
        public string HoleNumber { get; set; }
        public int Length { get; set; }
        public int Par { get; set; }            
        public int CourseID { get; set; }
        public decimal AvgScore { get; set; }

        public Course course { get; set; }
    }

    public class ScoreCard
    {
        public int ID { get; set; }
        public int Score { get; set; }
        public int Putts { get; set; }
        public bool FairwayInRegulation { get; set; }
        public bool GreenInRegulation { get; set; }
        public int HoleID { get; set; }
        public string Notes { get; set; }
        
        public Hole hole { get; set; }
    }

    public class User
    {

    }
}

GolfController/Controllers/HoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GolfController.Models;

namespace GolfController.Controllers
{ 
    public class HoleController : Controller
    {
        private HoleContext db = new HoleContext();

        //
        // GET: /Hole/

        public ViewResult Index()
        {
            var hole = db.hole.Include(h => h.course);
            return View(hole.ToList());
        }

        public ViewResult ViewHoles(int id)
        {
            var hole = db.hole.OrderBy(m=> m.HoleNumber).Where(m => m.CourseID == id);
                return View ( hole.ToList());
        }

       
        // GET: /Hole/Details/5
        public ViewResult Details(int id)
        {
            Hole hole = db.hole.Find(id);
            return View(hole);
        }

        //
        // GET: /Hole/Create

        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.course, "ID", "Name");
            return View();
        } 

        //
        // POST: /Hole/Create

        [HttpPost]
        public ActionResult Create(Hole hole)
        {
            if (ModelState.IsValid)
            {
                db.hole.Add(hole);              
                db.SaveChanges();
                CalculatePar(hole);
                CalculateLength(hole);
                return RedirectToAction("ViewHoles", new { id = hole.CourseID });  
            }

            ViewBag.CourseID = new SelectList(db.course, "ID", "Name", hole.CourseID);
            return View(hole);
        }
        
        private void CalculatePar(Hole hole)
        {
            var totalPar = (from item in db.hole
                                         where item.CourseID == hole.CourseID
                                         select item.Par).Sum();
            var course = db.course.Find(hole.CourseID);
            course.TotalPar = totalPar;
            db.SaveChanges();
        }

        private void CalculateLength(Hole hole)
        {
            var totalLength = (from item in db.hole
                            where item.CourseID == hole.CourseID
                            select item.Length).Sum();
            var course = db.course.Find(hole.CourseID);
            course.TotalLength = totalLength;
            db.SaveChanges();

        }
     

        //
        // GET: /Hole/Edit/5
 
        public ActionResult Edit(int id)
        {
            Hole hole = db.hole.Find(id);
            ViewBag.CourseID = new SelectList(db.course, "ID", "Name", hole.CourseID);
            return View(hole);
        }

        //
        // POST: /Hole/Edit/5

        [HttpPost]
        public ActionResult Edit(Hole hole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hole).State = EntityState.Modified;
                db.SaveChanges();
                CalculatePar(hole);
                CalculateLength(hole);
                return RedirectToAction("ViewHoles", new { id = hole.CourseID });
            }
            ViewBag.CourseID = new SelectList(db.course, "ID", "Name", hole.CourseID);
            return View(hole);
        }

        //
        // GET: /Hole/Delete/5
 
        public ActionResult Delete(int id)
        {
            Hole hole = db.hole.Find(id);
            return View(hole);
        }

        //
        // POST: /Hole/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Hole hole = db.hole.Find(id);
            db.hole.Remove(hole);
            db.SaveChanges();
            CalculatePar(hole);
            return RedirectToAction("ViewHoles", new { id = hole.CourseID });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GolfController/Controllers/ScoreCardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GolfController.Models;

namespace GolfController.Controllers
{ 
    public class ScoreCardController : Controller
    {
        private HoleContext db = new HoleContext();

        //
        // GET: /ScoreCard/

        public ViewResult Index(int id)
        {
            //var scorecard = db.scorecard.Include(s => s.hole).Where(h => h.HoleID == id );
            var scorecard = db.scorecard.Where(h => h.HoleID == id);
            return View(scorecard.ToList());
        }

        //
        // GET: /ScoreCard/Details/5

        public ViewResult Details(int id)
        {
            ScoreCard scorecard = db.scorecard.Find(id);
            return View(scorecard);
        }

        //
        // GET: /ScoreCard/Create
        [HttpGet]
        public ActionResult Create(int id)
        {
            ViewBag.HoleID = new SelectList(db.hole, "ID", "HoleNumber", id);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_Create");
            }
            ViewBag.HoleID = new SelectList(db.hole, "ID", "HoleNumber", id);
          
            return View();
        } 

        //
        // POST: /ScoreCard/Create

        [HttpPost]
        public ActionResult Create(ScoreCard scorecard)
        {
            // TODO: put in temp message that you need too refresh to see latest avg score 
            if (ModelState.IsValid)
            {
           
                db.scorecard.Add(scorecard);
                db.SaveChanges();
                CalculateAverageScore(scorecard.HoleID); 
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_ThanksForFeedback");
                  // return RedirectToAction("Hole", "ViewHoles", new { id = scorecard.hole.CourseID });
                }
                return RedirectToAction("Index");  
            }

            ViewBag.HoleID = new SelectList(db.hole, "ID", "HoleNumber", scorecard.HoleID);
            return View(scorecard);
        }
        
        //
        // GET: /ScoreCard/Edit/5
 
        public ActionResult Edit(int id)
        {
            ScoreCard scorecard = db.scorecard.Find(id);
            ViewBag.HoleID = new SelectList(db.hole, "ID", "HoleNumber", scorecard.HoleID);
            return View(scorecard);
        }

        //
        // POST: /ScoreCard/Edit/5

        [HttpPost]
        public ActionResult Edit(ScoreCard scorecard)
        {
            if (ModelState.IsValid)
            {
                db.Entry(scorecard).State = EntityState.Modified;
                
                db.SaveChanges();
                CalculateAverageScore(scorecard.HoleID); 
                return RedirectToAction("Index");
            }
            ViewBag.HoleID = new SelectList(db.hole, "ID", "HoleNumber", scorecard.HoleID);
            return View(scorecard);
        }

        //
        // GET: /ScoreCard/Delete/5
 
        public ActionResult Delete(int id)
        {
            ScoreCard scorecard = db.scorecard.Find(id);
            return View(scorecard);
        }

        //
        // POST: /ScoreCard/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            ScoreCard scorecard = db.scorecard.Find(id);
            db.scorecard.Remove(scorecard);
            db.SaveChanges();
            CalculateAverageScore(scorecard.HoleID);
            return RedirectToAction("Index", new { id = scorecard.HoleID });
        }

        
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public void CalculateAverageScore(int id)
        {                     
            var hole = db.hole.Find(id);
            var ifexists = db.scorecard.Any(m => m.HoleID == id);


            if (ifexists)
            {
                decimal number = db.scorecard.Where(m => m.HoleID == id).Count();
                var totalScore = (from item in db.scorecard
                                  where item.HoleID == id
                                  select item.Score).Sum();
                hole.AvgScore = totalScore / number;
                db.SaveChanges();

            }
            else
            {
                hole.AvgScore = 0;
                db.SaveChanges();
            
            }
                  

           

           





        }
    }
}

GolfController/Views/Hole/Create.cshtml
@model GolfController.Models.Hole

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Hole</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.HoleNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HoleNumber)
            @Html.ValidationMessageFor(model => model.HoleNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Length)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Length)
            @Html.ValidationMessageFor(model => model.Length)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Par)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Par)
            @Html.ValidationMessageFor(model => model.Par)
        </div>

 

        <div class="editor-label">
            @Html.LabelFor(model => model.CourseID, "course")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CourseID", String.Empty)
            @Html.ValidationMessageFor(model => model.CourseID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GolfController/Views/Hole/Delete.cshtml
@model GolfController.Models.Hole

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Hole</legend>

    <div class="display-label">HoleNumber</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HoleNumber)
    </div>

    <div class="display-label">Length</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Length)
    </div>

    <div class="display-label">Par</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Par)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">course</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.course.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

GolfController/Views/Hole/Details.cshtml
@model GolfController.Models.Hole

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Hole</legend>

    <div class="display-label">HoleNumber</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HoleNumber)
    </div>

    <div class="display-label">Length</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Length)
    </div>

    <div class="display-label">Par</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Par)
    </div>



    <div class="display-label">course</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.course.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GolfController/Views/Hole/Edit.cshtml
@model GolfController.Models.Hole

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Hole</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.HoleNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HoleNumber)
            @Html.ValidationMessageFor(model => model.HoleNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Length)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Length)
            @Html.ValidationMessageFor(model => model.Length)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Par)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Par)
            @Html.ValidationMessageFor(model => model.Par)
        </div>

    

        <div class="editor-label">
            @Html.LabelFor(model => model.CourseID, "course")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CourseID", String.Empty)
            @Html.ValidationMessageFor(model => model.CourseID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GolfController/Views/Hole/Index.cshtml
@model IEnumerable<GolfController.Models.Hole>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            HoleNumber
        </th>
        <th>
            Length
        </th>
        <th>
            Par
        </th>
        <th>
            Description
        </th>
        <th>
            course
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HoleNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Length)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Par)
        </td>
     
        <td>
            @Html.DisplayFor(modelItem => item.course.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

GolfController/Views/Hole/ViewHoles.cshtml
@model IEnumerable<GolfController.Models.Hole>

@{
    ViewBag.Title = "ViewHoles";
}


<h2>ViewHoles</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            HoleNumber
        </th>
        <th>
            Length
        </th>
        <th>
            Par
        </th>
        <th>
            CourseID
        </th>
        <th>
            AvgScore
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HoleNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Length)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Par)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CourseID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AvgScore)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })|
             @Html.ActionLink("Register Score", "Create", "ScoreCard", new { id = item.ID }, new { @class = "openDialog", data_dialog_id = "ScoreCardDialog", data_dialog_title = "ScoreCard" })|
             @Html.ActionLink("View Score", "Index" ,"ScoreCard", new { id=item.ID } , null )
       
        </td>
    </tr>
}

</table>