GolfController/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GolfController.Models;

namespace GolfController.Controllers
{ 
    public class CourseController : Controller
    {
        private HoleContext db = new HoleContext();

        //
        // GET: /Course/

        public ViewResult Index()
        {
           
          return View(db.course.ToList());
        }

        //
        // GET: /Course/Details/5

        public ViewResult Details(int id)
        {
            Course course = db.course.Find(id);
            return View(course);
        }

        //
        // GET: /Course/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Course/Create

        [HttpPost]
        public ActionResult Create(Course course)
        {
            if (ModelState.IsValid)
            {
                db.course.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(course);
        }
        
        //
        // GET: /Course/Edit/5
 
        public ActionResult Edit(int id)
        {
            Course course = db.course.Find(id);
            return View(course);
        }

        //
        // POST: /Course/Edit/5

        [HttpPost]
        public ActionResult Edit(Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(course);
        }

        //
        // GET: /Course/Delete/5
 
        public ActionResult Delete(int id)
        {
            Course course = db.course.Find(id);
            return View(course);
        }

        //
        // POST: /Course/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Course course = db.course.Find(id);
            db.course.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GolfController/Controllers/HoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GolfController.Models;

namespace GolfController.Controllers
{ 
    public class HoleController : Controller
    {
        private HoleContext db = new HoleContext();

        //
        // GET: /Hole/

        public ViewResult Index()
        {
            var hole = db.hole.Include(h => h.course);
            return View(hole.ToList());
        }

        public ViewResult ViewHoles(int id)
        {
            var hole = db.hole.OrderBy(m=> m.HoleNumber).Where(m => m.CourseID == id);
                return View ( hole.ToList());
        }

       
        // GET: /Hole/Details/5
        public ViewResult Details(int id)
        {
            Hole hole = db.hole.Find(id);
            return View(hole);
        }

        //
        // GET: /Hole/Create

        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.course, "ID", "Name");
            return View();
        } 

        //
        // POST: /Hole/Create

        [HttpPost]
        public ActionResult Create(Hole hole)
        {
            if (ModelState.IsValid)
            {
                db.hole.Add(hole);              
                db.SaveChanges();
                CalculatePar(hole);
                CalculateLength(hole);
                return RedirectToAction("ViewHoles", new { id = hole.CourseID });  
            }

            ViewBag.CourseID = new SelectList(db.course, "ID", "Name", hole.CourseID);
            return View(hole);
        }
        
        private void CalculatePar(Hole hole)
        {
            var totalPar = (from item in db.hole
                                         where item.CourseID == hole.CourseID
                                         select item.Par).Sum();
            var course = db.course.Find(hole.CourseID);
            course.TotalPar = totalPar;
            db.SaveChanges();
        }

        private void CalculateLength(Hole hole)
        {
            var totalLength = (from item in db.hole
                            where item.CourseID == hole.CourseID
                            select item.Length).Sum();
            var course = db.course.Find(hole.CourseID);
            course.TotalLength = totalLength;
            db.SaveChanges();

        }
     

        //
        // GET: /Hole/Edit/5
 
        public ActionResult Edit(int id)
        {
            Hole hole = db.hole.Find(id);
            ViewBag.CourseID = new SelectList(db.course, "ID", "Name", hole.CourseID);
            return View(hole);
        }

        //
        // POST: /Hole/Edit/5

        [HttpPost]
        public ActionResult Edit(Hole hole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hole).State = EntityState.Modified;
                db.SaveChanges();
                CalculatePar(hole);
                CalculateLength(hole);
                return RedirectToAction("ViewHoles", new { id = hole.CourseID });
            }
            ViewBag.CourseID = new SelectList(db.course, "ID", "Name", hole.CourseID);
            return View(hole);
        }

        //
        // GET: /Hole/Delete/5
 
        public ActionResult Delete(int id)
        {
            Hole hole = db.hole.Find(id);
            return View(hole);
        }

        //
        // POST: /Hole/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Hole hole = db.hole.Find(id);
            db.hole.Remove(hole);
            db.SaveChanges();
            CalculatePar(hole);
            return RedirectToAction("ViewHoles", new { id = hole.CourseID });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GolfController/Views/Course/Create.cshtml
@model GolfController.Models.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Course</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NumberOfHoles)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NumberOfHoles)
            @Html.ValidationMessageFor(model => model.NumberOfHoles)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TotalLength)
        </div>       

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GolfController/Views/Course/Delete.cshtml
@model GolfController.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Course</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">NumberOfHoles</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumberOfHoles)
    </div>

    <div class="display-label">TotalLength</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TotalLength)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

GolfController/Views/Course/Details.cshtml
@model GolfController.Models.Course

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Course</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">NumberOfHoles</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumberOfHoles)
    </div>

    <div class="display-label">TotalLength</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TotalLength)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Add course", "Create", "Hole");
</p>

GolfController/Views/Course/Edit.cshtml
@model GolfController.Models.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Course</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NumberOfHoles)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NumberOfHoles)
            @Html.ValidationMessageFor(model => model.NumberOfHoles)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TotalLength)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TotalLength)
            @Html.ValidationMessageFor(model => model.TotalLength)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GolfController/Views/Course/Index.cshtml
@model IEnumerable<GolfController.Models.Course>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table>
    <tr>
        <th>
            Name
        </th>
        <th>
            Holes
        </th>
        <th>
         Par
        </th>
        <th>
        Total Length
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfHoles)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPar)
        </td>
           <td>
            @Html.DisplayFor(modelItem => item.TotalLength)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })  |
            @Html.ActionLink("View Holes", "ViewHoles" , "Hole", new { id=item.ID } , null ) 

        </td>
    </tr>
}

</table>